version: '3.9'

services:
  weather.api:
    container_name: weather.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
     - my_db:/app/Db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "8000:80"
