apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: host-pvc
spec:
  volumeName: host-pv
  storageClassName: standard
  accessModes: 
    - ReadWriteOnce
  resources:
    request:
      storage: 1Gi